apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: frontend
    track: canary
  name: frontend-canary
spec:
  replicas: 2
  template:
    metadata:
      labels:
        service: frontend
        api: external
        track: canary
    spec:
      containers:
      - image: myluc/udacity-frontend:V7
        name: frontend
        imagePullPolicy: Always          
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"                
      restartPolicy: Always

