apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: frontend
    track: stable
  name: frontend
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        service: frontend
        api: external
        track: stable
    spec:
      containers:
      - image: myluc/udacity-frontend:V4
        name: frontend
        imagePullPolicy: Always          
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"                
      restartPolicy: Always

